services:
 - name: /wolf_panel/remove_widget
   type: rt_gui/Void
 - name: /wolf_panel/add_trigger
   type: rt_gui/Void
 - name: /wolf_panel/add_text
   type: rt_gui/Text
 - name: /wolf_panel/add_list
   type: rt_gui/List
 - name: /wolf_panel/add_label
   type: rt_gui/Text
 - name: /wolf_panel/add_int
   type: rt_gui/Int
 - name: /wolf_panel/add_double
   type: rt_gui/Double
 - name: /wolf_panel/add_bool
   type: rt_gui/Bool
 - name: /task_interface/update_trigger
   type: rt_gui/Void
 - name: /task_interface/update_text
   type: rt_gui/Text
 - name: /task_interface/update_list
   type: rt_gui/List
 - name: /task_interface/update_label
   type: rt_gui/Text
 - name: /task_interface/update_int
   type: rt_gui/Int
 - name: /task_interface/update_double
   type: rt_gui/Double
 - name: /task_interface/update_bool
   type: rt_gui/Bool
   
   
   
   






